#!/bin/bash

sudo systemctl stop klipper || true
. ~/klipper_config/klipper.config

: "${BOARD:?'Please export a BOARD variable'}"
: "${SERIAL:?'Please export a SERIAL variable'}"

if [ "$USE_RPI" == "yes" ] ; then
  if [ ! -f /etc/init.d/klipper_mcu ]; then
    sudo cp ~/klipper/scripts/klipper-mcu-start.sh /etc/init.d/klipper_mcu
    sudo update-rc.d klipper_mcu defaults
  fi
  sudo systemctl stop klipper_mcu || true
fi

pushd ~/klipper >/dev/null
  echo "Updating klipper"
  git pull

  if [ -f "$SERIAL" ]; then
    echo "Building $BOARD mcu"
    make clean KCONFIG_CONFIG=~/klipper_config/config.$BOARD
    # make menuconfig KCONFIG_CONFIG=config.$BOARD
    make KCONFIG_CONFIG=~/klipper_config/config.$BOARD
    ./scripts/flash-sdcard.sh "$SERIAL" "$BOARD"
    /bin/cp -fv out/klipper.elf ~/klipper_config/FIRMWARE.BIN
  else
    echo "Could not find SERIAL:${SERIAL} - skipping"
  fi
  if [ "$USE_RPI" == "yes" ]; then
    echo "Building rpi mcu"
    make clean KCONFIG_CONFIG=~/klipper_config/config.rpi
    # make menuconfig KCONFIG_CONFIG=config.rpi
    make flash KCONFIG_CONFIG=~/klipper_config/config.rpi
    cp out/klipper.bin ~/klipper_config/klipper.rpi
    sudo systemctl start klipper_mcu || true
  fi
  sudo systemctl start klipper
  VER=$(git -C . describe --tags --long --dirty)
  echo "git commit -m \"feat(PRN): klipper compiled at $VER\""
popd >/dev/null
